Simulink.defineIntEnumType( 'IDT_PowerState', ...
   {'NOK','OK'}, ...
   [0 1], ...
   'DefaultValue', 'NOK', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

