# ------------------------------------------------------------------
# Global config file for BTC EmbeddedPlatform CI workflow
# 
# - this config is merged with a project-specific config (if present)
# - the project-specific config has precedence in case of conflicts
# ------------------------------------------------------------------

# General settings
matlabVersion: MATLAB R2018b (64-bit)
compiler: MinGW64 (64bit)
installationRoot: C:/Program Files/BTC
epVersion: 2.11p1