name: BTC Unit Tests for Simulink Models

# run on push if there are changes in the paths listed below
on:
  push:
    paths:
      - .github/workflows/test_sl.yml
      - examples/test_workflow_sl.py
      - examples/Simulink_PWC/**
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # Runs on a pre-configured VM with 
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: cmd

      - name: Run test workflow
        run:  python -u examples/test_workflow_sl.py "${{github.workspace}}/examples/Simulink_PWC/pwc_sl.epp"
        
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: |
            examples/Simulink_PWC/pwc_sl.epp
            examples/Simulink_PWC/report.html
          